plugins {
    id 'org.springframework.boot'   // 실행 가능한 앱 (버전은 루트에 등록됨)
}

dependencies {
    // 버전이 없어도 되는 이유: Step 1에서 깔아둔 Spring Cloud BOM이 채워준다
    // common이 없다! 디스커버리 서버는 우리 도메인과는 전혀 상과없는 인프라 컴포넌트이기 때문.
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-server'
}
