plugins {
	// 루트에서는 버전만 등록하고, 실제 적용은 이제부터 각 모듈에서 한다.
	id 'org.springframework.boot' version '4.1.0' apply false
	id 'io.spring.dependency-management' version '1.1.7' apply false
}

allprojects {
    group = 'com.growmighty.lectures.firstday'
    version = '0.0.1-SNAPSHOT'

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'io.spring.dependency-management'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    // common처럼 Boot 플러그인 대상이 아닌 모듈도 Spring Boot BOM으로
    // 의존성 버전을 통일해서 관리한다. 즉, Boot 플러그인 대상이 아니더라도
    // 우리가 정의해 둔 BOM은 나중에 딴소리 말고 꼭 알아둬라 라는 의미이다.
    // BOM은 검증된 버전 목록을 하나의 표로 만들어 둔 것이다.
    dependencyManagement {
        imports {
            mavenBom org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES
        }
    }

    dependencies {
        // 모듈이 공통으로 쓰는 것만 여기에 넣는다. 롬복같은 것들이 있겠다.
        compileOnly 'org.projectlombok:lombok'
        annotationProcessor 'org.projectlombok:lombok'
        testCompileOnly 'org.projectlombok:lombok'
        testAnnotationProcessor 'org.projectlombok:lombok'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }

    tasks.named('test') {
        useJUnitPlatform()
    }
}
