# 설정 파일도 각 서비스마다 모두 다 만들어줘야 한다.

spring.application.name=product-service
# 포트 번호를 모두 다 다르게 해야 한다!
server.port=8083

# 서비스마다 자기만의 DB를 갖는다 (Database per Service)
spring.datasource.url=jdbc:h2:mem:productdb;DB_CLOSE_DELAY=-1
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
