spring.application.name=order-service
server.port=8080

spring.datasource.url=jdbc:h2:mem:orderdb;DB_CLOSE_DELAY=-1
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# 이 두 줄이 "base-url만 바꾸면 MSA"의 실체.
# 배포 환경에서는 http://product-service.internal 같은 주소로만 바꾸면 된다.
# 하지만 우리가 알려줬다. 손으로. 직접 하드코딩해서. -> 세 가지 문제점이 있음.
# 그래서 이렇게 한다. 유레카!
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# 얘네 둘의 구체적인 주소? 이제부터 알 바 아님.
order.client.product-base-url=http://product-service
order.client.payment-base-url=http://payment-service
